kind: pipeline
name: default

steps:
- name: cloning repo
  image: alpine:3.10.2
  volumes:
    - name: repo
      path: /order/
  commands:
    - cd /
    - apk update
    - apk add git
    - git clone "https://github.com/rewanth1997/kubectl-fields" /order

- name: building repo
  image: golang:alpine
  volumes:
    - name: repo
      path: /order/
  commands:
    - cp -r /order $GOPATH/src/
    - cd $GOPATH/src/order
    - apk add git
    - go get ./...
    - go build -o /order/order_exe main.go
    - /order/order_exe -h
    
- name: running test cases
  image: golang:alpine
  volumes:
    - name: repo
      path: /order/
  commands:
    - mv /order/order_exe /usr/bin/kubectl-fields # Move executable to global PATH

    - cd /order/.pipeline
    
    # kubectl explain --recursive po.spec | order capa
    - cat test-cases/po.spec.txt | kubectl-fields --stdin capa > /tmp/po.spec_capa.sol
    - diff /tmp/po.spec_capa.sol test-cases/po.spec_capa.sol
    
    # kubectl explain --recursive configMap.metadata.initializers | order -i uid
    - cat test-cases/configMap.metadata.initializers.txt | kubectl-fields --stdin -i uid > /tmp/configMap.metadata.initializers_uid_i.sol
    - diff /tmp/configMap.metadata.initializers_uid_i.sol test-cases/configMap.metadata.initializers_uid_i.sol
    
    # kubectl explain --recursive ingress.spec.rules | order service
    - cat test-cases/ingress.spec.rules.txt | kubectl-fields --stdin service > /tmp/ingress.spec.rules_service.sol
    - diff /tmp/ingress.spec.rules_service.sol test-cases/ingress.spec.rules_service.sol
    
    # kubectl explain --recursive po | order ver
    - cat test-cases/po.txt | kubectl-fields --stdin ver > /tmp/po_ver.sol
    - diff /tmp/po_ver.sol test-cases/po_ver.sol
    
    # kubectl explain --recursive svc.spec | order -i port
    - cat test-cases/svc.spec.txt | kubectl-fields --stdin -i port > /tmp/svc.spec_port_i.sol
    - diff /tmp/svc.spec_port_i.sol test-cases/svc.spec_port_i.sol
    
    # kubectl explain --recursive svc | order -i ip
    - cat test-cases/svc.txt | kubectl-fields --stdin -i ip > /tmp/svc_ip_i.sol
    - diff /tmp/svc_ip_i.sol test-cases/svc_ip_i.sol
    
    # kubectl explain daemonsets.spec.template --recursive | order -i secretref
    - cat test-cases/daemonsets.spec.template.txt | kubectl-fields --stdin -i secretref > /tmp/daemonsets.spec.template_secretref_i.sol
    - diff /tmp/daemonsets.spec.template_secretref_i.sol test-cases/daemonsets.spec.template_secretref_i.sol
    
    - echo "Everything looks great"
    
volumes:
- name: repo
  temp: {}
