kind: pipeline
name: default

steps:
- name: cloning repo
  image: alpine:3.10.2
  volumes:
    - name: repo
      path: /order/
  commands:
    - cd /
    - apk update
    - apk add git
    - git clone "https://github.com/testinguser883/webapp" /order

volumes:
- name: repo
  temp: {}
