kind: pipeline
name: default

steps:
- name: cloning repo
  image: alpine:3.10.2
  volumes:
    - name: repo
      path: /order/
  commands:
    - cd /
    - apk update
    - apk add git
    - git clone "https://github.com/rewanth1997/order"

# - name: testing volumes
#   image: golang:alpine
#   volumes:
#     - name: repo
#       path: /order/
#   commands:
#     - ls -la order
#     - echo "#######################"
#     - ls -la /order
    
- name: building repo
  image: golang:alpine
  volumes:
    - name: repo
      path: /order/
  commands:
    - cp -r /order $GOPATH/src/
    - cd $GOPATH/src/order
    - ls -la
    - apk add git
    - go get ./...
    - go build -o /order/order_exe main.go
    - ls -la /order
    - /order/order_exe -h

volumes:
- name: repo
  temp: {}
